Employee_management_system_A/Employee/urls.py
from django.urls import path

from .views import EmployeeListView, EmployeeCreateView, EmployeeDetailView, BranchCreateView, BranchListView, \
    EmployeeUpdateView, EmployeeDeleteView

app_name = "Employee"

urlpatterns = [
    path('employee/list/', EmployeeListView.as_view(), name="employee_list_view"),
    path('employee/create/', EmployeeCreateView.as_view(), name="employee_create_view"),
    path('employee/edit/<int:pk>/', EmployeeUpdateView.as_view(), name="employee_edit_view"),
    path('employee/delete/<int:pk>/', EmployeeDeleteView.as_view(), name="employee_delete_view"),
    path('employee/<int:pk>/', EmployeeDetailView.as_view(), name="employee_detail_view"),
    path('branch/create/', BranchCreateView.as_view(), name="branch_create_view"),
    path('branch/list/', BranchListView.as_view(), name="branch_list_view"),
]

Employee_management_system_A/Employee_management_system_A/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Employee.views import DashboardView

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', DashboardView.as_view(),),
                  path('', include('Employee.urls')),
                  path('dashboard/', DashboardView.as_view(), name='dashboard'),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('search/', include('haystack.urls')),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL,
                                                                                           document_root=settings.MEDIA_ROOT)

Employee_management_system_A/Employee/models.py
from django.contrib.auth.models import Group, User
from django.db import models


# Create your models here.

def upload_location(instance, filename):
    file_path = 'Images/{name}/{filename}'.format(
        name=str(instance.full_name), filename=filename)
    return file_path


class Designation(models.Model):
    designation = models.CharField(max_length=120)
    group = models.ForeignKey(Group, on_delete=models.PROTECT, null=True)

    def __str__(self):
        return self.designation


class Branch(models.Model):
    branch_name = models.CharField(max_length=120)
    location = models.CharField(max_length=120)
    information = models.TextField(max_length=500, null=True, blank=True)
    phone_no = models.CharField(max_length=20)

    def __str__(self):
        return self.branch_name


class Employee(models.Model):
    related_user = models.OneToOneField(User, on_delete=models.CASCADE, null=True, blank=True, related_name='employee')
    full_name = models.CharField(max_length=150, blank=False)
    gender = models.CharField(max_length=50, blank=False)
    address = models.CharField(max_length=150, blank=False)
    designation = models.ForeignKey(Designation, on_delete=models.PROTECT)
    father_name = models.CharField(max_length=150, blank=False)
    mother_name = models.CharField(max_length=150, blank=False)
    join_date = models.DateField(blank=False)
    branch = models.ForeignKey(Branch, on_delete=models.PROTECT)
    pan_no = models.CharField(max_length=120, null=True)
    contact_no = models.CharField(max_length=20, blank=False)
    left_date = models.DateField(null=True, blank=True)
    goods_provided = models.CharField(max_length=200, null=True)
    reference_by = models.CharField(max_length=120, null=True)
    bio = models.TextField(max_length=500, null=True)
    photo = models.ImageField(upload_to=upload_location, blank=False)
    passport_or_citizenship = models.ImageField(upload_to=upload_location, blank=False)
    family_photo = models.ImageField(upload_to=upload_location, null=True, blank=True)

    def __str__(self):
        return self.full_name

    def delete(self, using=None, keep_parents=False):
        self.photo.storage.delete(self.photo.name)
        self.passport_or_citizenship.storage.delete(self.passport_or_citizenship.name)
        if self.family_photo:
            self.family_photo.storage.delete(self.family_photo.name)
        super().delete()

Employee_management_system_A/Employee/forms.py
from django import forms

from .models import Employee, Branch


class TextInputWidget(forms.TextInput):
    attrs = {'class': "form-control"}

    class Media:
        pass


class DateInputWidget(forms.DateInput):
    attrs = {'class': "form-control", 'type': "date"}

    class Media:
        pass


class EmployeeForm(forms.ModelForm):
    join_date = forms.DateField(widget=forms.DateInput(attrs={'type': "date"}))
    left_date = forms.DateField(widget=forms.DateInput(attrs={'type': "date"}), required=False)
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': "form-control"}))
    passport_or_citizenship = forms.ImageField(widget=forms.FileInput(attrs={'class': "form-control"}))
    family_photo = forms.ImageField(widget=forms.FileInput(attrs={'class': "form-control"}), required=False)
    pan_no = forms.CharField(widget=forms.NumberInput())
    contact_no = forms.CharField(widget=forms.NumberInput())
    bio = forms.CharField(widget=forms.Textarea(), required=False)
    goods_provided = forms.CharField(required=False)

    class Meta:
        model = Employee
        fields = ['full_name', 'gender', 'address', 'designation', 'father_name', 'mother_name', 'join_date', 'branch',
                  'pan_no', 'contact_no', 'left_date', 'goods_provided', 'reference_by', 'bio', 'photo',
                  'passport_or_citizenship',
                  'family_photo']


class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = '__all__'

Employee_management_system_A/Employee/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import EmployeeForm, BranchForm
from .models import Employee, Branch, Designation


# Create your views here.


class EmployeeListView(LoginRequiredMixin, ListView):
    model = Employee
    form_class = EmployeeForm
    template_name = "employee_list.html"
    context_object_name = 'employee_list'
    permission_required = ('Employee.view_employee', 'Branch.view_branch')
    permission_denied_message = "You DoNot Have Necessary Permissions"


class EmployeeUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Employee
    form_class = EmployeeForm
    template_name = "employee_edit.html"
    success_url = '/'
    success_message = 'Employee Updated successfully'
    error_message = 'Error Updating Employee'


class EmployeeDeleteView(LoginRequiredMixin, SuccessMessageMixin, DeleteView):
    model = Employee
    form_class = EmployeeForm
    success_url = '/'
    success_message = 'Employee Deleted successful'


class EmployeeCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Employee
    fields = '__all__'
    template_name = "employee_create.html"
    permission_required = ('Employee.create_employee', 'Employee.view_employee', 'Branch.view_branch')
    permission_denied_message = "You DoNot Have Necessary Permissions"

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            form = EmployeeForm(request.POST, request.FILES)
            if form.is_valid():
                messages.add_message(request, messages.INFO, 'Employee added successfully !')
                form.save()
                return redirect("Employee:employee_create_view")
            else:
                context = {}
                context['error'] = form.errors
                context['form'] = form
                messages.add_message(request, messages.ERROR, 'Employee creation Failed!')
                return render(request, template_name="employee_create.html", context=context)
        else:
            render(request, template_name="employee_create.html")

    def get_context_data(self, **kwargs):
        context = super(EmployeeCreateView, self).get_context_data(**kwargs)
        context['branch_list'] = Branch.objects.all()
        context['designation_list'] = Designation.objects.all()
        context['form'] = EmployeeForm()
        return context


class EmployeeDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    queryset = Employee.objects.select_related('designation', 'branch')
    model = Employee
    form_class = EmployeeForm
    template_name = "employee_details.html"
    context_object_name = 'employee_detail'
    permission_required = ('Employee.view_employee',)
    permission_denied_message = "You DoNot Have Necessary Permissions"


class BranchCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Branch
    fields = '__all__'
    template_name = 'branch_create.html'
    permission_required = ('Branch.create_branch', 'Branch.view_branch')
    permission_denied_message = "You DoNot Have Necessary Permissions"

    def post(self, request, *args, **kwargs):
        if request.method == 'POST':
            form = BranchForm(request.POST)
            if form.is_valid():
                form.save()
                messages.add_message(request, messages.INFO, 'Branch added successfully !')
                return redirect("Employee:branch_list_view")
            else:
                context = {}
                context['error'] = form.errors
                context['form'] = form
                messages.add_message(request, messages.ERROR, 'Branch creation Failed!')
                return render(request, template_name="branch_create.html", context=context)
        else:
            render(request, template_name="branch_create.html")


class BranchListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Branch
    fields = '__all__'
    template_name = 'branch_list.html'
    context_object_name = 'branch_list'
    permission_required = ('Branch.crate_branch', 'Branch.view_branch')
    permission_denied_message = "You DoNot Have Necessary Permissions"


class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = "dashboard.html"

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        employee_list = Employee.objects.all()
        context['employee_number'] = len(employee_list)
        context['branch_number'] = Branch.objects.all().count()
        context['designation_number'] = Designation.objects.all().count()
        context['employee_list'] = employee_list
        return context

Employee_management_system_A/Employee/templates/branch_create.html
{% extends "base.html"%}
{% block content%}
{% load crispy_forms_tags %}
<!-- Main Content -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <form class="needs-validation" novalidate="" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="card-header">
                    <h4> Create Employee</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        {% for field in form %}
                        <div class="col-lg-4 col-md-6 col-sm-12">
                            {{ field|as_crispy_field }}
                            <div class="invalid-feedback">
                                Required
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">Submit
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

<!-- main container -->
{% endblock content%}

Employee_management_system_A/Employee/templates/branch_list.html
{% extends "base.html"%}

{% block content%}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Employee List</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="table-1">
                        <thead>
                        <tr>
                            <th class="text-center">
                                #
                            </th>
                            <th>Name</th>
                            <th>Location</th>
                            <th>Phone NO</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for branch in branch_list %}
                        <tr>
                            <td>
                                {{branch.id}}
                            </td>
                            <td>{{branch.branch_name}}</td>
                            <td >
                               {{branch.location}}

                            </td>

                            <td>{{branch.phone_no}}</td>


                        </tr>
                        {% endfor%}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

Employee_management_system_A/Employee/templates/dashboard.html
{% extends "base.html"%}
{% load static%}
{% block css%}
{% endblock css%}


{% block content%}
<div class="row ">
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="card">
            <div class="card-statistic-4">
                <div class="align-items-center justify-content-between">
                    <div class="row ">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pr-0 pt-3">
                            <div class="card-content">
                                <h5 class="font-15">Total Employee</h5>
                                <h2 class="mb-3 font-18">{{employee_number}}</h2>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pl-0">
                            <div class="banner-img">
                                <img src="{% static 'assets/img/ems_images/employee.png'%}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="card">
            <div class="card-statistic-4">
                <div class="align-items-center justify-content-between">
                    <div class="row ">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pr-0 pt-3">
                            <div class="card-content">
                                <h5 class="font-15"> Branach</h5>
                                <h2 class="mb-3 font-18">{{branch_number}}</h2>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pl-0">
                            <div class="banner-img">
                                <img src="{% static 'assets/img/ems_images/branch.png'%}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="card">
            <div class="card-statistic-4">
                <div class="align-items-center justify-content-between">
                    <div class="row ">
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pr-0 pt-3">
                            <div class="card-content">
                                <h5 class="font-15">Designation</h5>
                                <h2 class="mb-3 font-18">{{designation_number}}</h2>
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 pl-0">
                            <div class="banner-img">
                                <img src="{% static 'assets/img/ems_images/designation.png'%}" alt="">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Employee List</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="table-1">
                        <thead>
                        <tr>
                            <th class="text-center">
                                #
                            </th>
                            <th>Name</th>
                            <th>Designation</th>
                            <th>Photo</th>
                            <th>Branch</th>
                            <th>Contact No</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for employee in employee_list%}
                        <tr>
                            <td>
                                {{forloop.counter}}
                            </td>
                            <td>{{employee.full_name}}</td>
                            <td >
                               {{employee.designation}}
                            </td>
                            <td>
                                <img alt="image" src="{{employee.photo.url}}" width="35">
                            </td>
                            <td>{{employee.branch}}</td>
                            <td>
                               {{employee.contact_no}}
                            </td>
                            <td><a href="{%url 'Employee:employee_detail_view' employee.id %}" class="btn btn-primary">Detail</a></td>
                        </tr>
                        {% endfor%}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascript %}
<script src="{% static 'assets/bundles/apexcharts/apexcharts.min.js'%}"></script>
<!-- Page Specific JS File -->
<script src="{% static 'assets/js/page/index.js'%}"></script>
{% endblock javascript%}

Employee_management_system_A/Employee/templates/designation_create.html
{% extends "base.html"%}
{% block content%}
{% load crispy_forms_tags %}
<!-- Main Content -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <form class="needs-validation" novalidate="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-header">
                    <h4> Create Employee</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        {% for field in form %}
                        <div class="col-4">
                            {{ field|as_crispy_field }}
                            <div class="invalid-feedback">
                                Required
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                 <div class="card-footer">
                    <button class="btn btn-primary" type="submit" >Submit
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

<!-- main container -->
{% endblock content%}

Employee_management_system_A/Employee/templates/employee_create.html
{% extends "base.html"%}
{% block content%}
{% load crispy_forms_tags %}
<!-- Main Content -->
<div class="row">
    <div class="col-12">
        <div class="card">
            <form class="needs-validation" novalidate="" method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                <div class="card-header">
                    <h4> Create Employee</h4>
                </div>
                <div class="card-body">
                    <div class="row">
                        {% for field in form %}
                        <div class="col-lg-4 col-md-6 col-xs-12">
                            {{ field|as_crispy_field }}
                            <div class="invalid-feedback">
                                Required
                            </div>
                        </div>
                        {% endfor %}
                    </div>
                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit" >Submit
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

<!-- main container -->
{% endblock content%}

Employee_management_system_A/Employee/templates/employee_details.html
{% extends "base.html"%}
{% load static %}
{% block content%}
<div class="row ">
    <div class="col-12 col-md-12 col-lg-4">
        <div class="card author-box">
            <div class="card-body">
                <div class="author-box-center">
                    <img alt="image" src="{{employee_detail.photo.url}}" class="rounded-circle author-box-picture">
                    <div class="clearfix"></div>
                    <div class="author-box-name">
                        <a href="#">{{employee_detail.full_name}}</a>
                    </div>
                    <div class="author-box-job"><strong>{{employee_detail.designation}}</strong> In
                        <strong>{{employee_detail.branch}}</strong>
                    </div>
                </div>
                <div class="author-box-center">

                    <p class="text-muted">Reference By:<strong>{{employee_detail.reference_by}}</strong></p>
                </div>

                <div class="text-center">
                    <div class="author-box-description">
                        <p>
                            {{employee_detail.bio}}
                        </p>
                    </div>
                    <div class="w-100 d-sm-none"></div>
                </div>
            </div>
        </div>
        <div class="card">
            <div class="card-header">
                <h4>Branch Details</h4>
            </div>
            <div class="card-body">
                <div class="py-4">
                    <p class="clearfix">
                        <span class="float-left">
                            Branch Name
                        </span>
                        <span class="float-right text-muted">
                            {{employee_detail.branch.branch_name}}
                        </span>
                    </p>
                    <p class="clearfix">
                        <span class="float-left">
                            Phone
                        </span>
                        <span class="float-right text-muted">
                            {{employee_detail.branch.phone_no}}
                        </span>
                    </p>
                    <p class="clearfix">
                        <span class="float-left">
                            Location
                        </span>
                        <span class="float-right text-muted">
                            {{employee_detail.branch.location}}
                        </span>
                    </p>

                </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-md-12 col-lg-8">
        <div class="card">
            <div class="padding-20">
                <div class="row">
                    <div class="col-6 b-r">
                        <strong>Mobile</strong>
                        <br>
                        <p class="text-muted">{{employee_detail.contact_no}}</p>
                    </div>
                    <div class=" col-6">
                        <strong>gender</strong>
                        <br>
                        <p class="text-muted">{{employee_detail.gender}}</p>
                    </div>
                    <div class=" col-6">
                        <strong>Father Name</strong>
                        <br>
                        <p class="text-muted">{{employee_detail.father_name}}</p>
                    </div>
                    <div class=" col-6">
                        <strong>Mother Name</strong>
                        <br>
                        <p class="text-muted">{{employee_detail.mother_name}}</p>
                    </div>
                    <div class=" col-6">
                        <strong>Address</strong>
                        <br>
                        <p class="text-muted">{{employee_detail.address}}</p>
                    </div>
                    <div class=" col-6">
                        <strong>Pan No</strong>
                        <br>
                        <p class="text-muted">{{employee_detail.pan_no}}</p>
                    </div>
                </div>
                <div class="row">
                    {% if employee_detail.family_photo%}
                    <div class="col-6 ">
                        <div class="card">
                            <div class="card-header">
                                <strong>Family Photo</strong>
                            </div>
                            <div class="card-body">
                                <div id="aniimated-thumbnials" class="row clearfix">
                                    <a href="{{employee_detail.family_photo.url}}" data-sub-html="Demo Description"
                                        target="_blank">
                                        <img class="img-responsive thumbnail" src="{{employee_detail.family_photo.url}}"
                                            alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {%endif%}
                    <div class="col-6">
                        <div class="card">
                            <div class="card-header">
                                <strong>Passport/citizinship</strong>
                            </div>
                            <div class="card-body">
                                <div id="aniimated-thumbnials" class="row clearfix">
                                    <a href="{{employee_detail.passport_or_citizenship.url}}"
                                        data-sub-html="Demo Description" target="_blank">
                                        <img class="img-responsive thumbnail"
                                            src="{{employee_detail.passport_or_citizenship.url}}" alt="">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% if perms.Employee.change_employee %}
<a href="{%url 'Employee:employee_edit_view' employee_detail.id %}" class="btn btn-primary">Edit</a>
{% endif%}
{% if perms.Employee.delete_employee %}
<button class="btn btn-danger" onclick="deleteEmployee({{employee_detail.id}})">Delete</button>
{% endif %}
{% endblock content%}
{% block javascript%}
<script src="{% static 'assets/js/page/portfolio.js'%}"></script>
<script>
    let deleteEmployee = ((id) => {
        swal({
            title: 'Are you sure?',
            text: 'Once deleted, you will not be able to recover Employee date!',
            icon: 'warning',
            buttons: true,
            dangerMode: true,
        }).then((willDelete) => {
            if (willDelete) {
                $.ajax({
                    type: 'POST',
                    url: "{% url 'Employee:employee_delete_view' employee_detail.id %}",
                    data: {
                        'csrfmiddlewaretoken': "{{ csrf_token }}"
                    },

                    success: (response) => {
                        console.log(response);
                        swal({
                            title: 'Poof! Employee has been deleted!',
                            icon: 'success',
                        }).then(value => {
                            if (value) {
                                window.location = "{% url 'dashboard'%}"
                            }
                        })

                    },
                    error: function () {
                        swal({
                            title: 'Employee delete Error ',
                            icon: 'error'
                        })
                    }
                })


            }
        })
    });
</script>
{% endblock javascript%}

Employee_management_system_A/Employee/templates/employee_list.html
{% extends "base.html"%}

{% block content%}
<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-header">
                <h4>Employee List</h4>
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-striped" id="table-1">
                        <thead>
                        <tr>
                            <th class="text-center">
                                #
                            </th>
                            <th>Name</th>
                            <th>Designation</th>
                            <th>Photo</th>
                            <th>Branch</th>
                            <th>Contact No</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for employee in employee_list%}
                        <tr>
                            <td>
                                {{forloop.counter}}
                            </td>
                            <td>{{employee.full_name}}</td>
                            <td >
                               {{employee.designation}}
                            </td>
                            <td>
                                <img alt="image" src="{{employee.photo.url}}" width="35">
                            </td>
                            <td>{{employee.branch}}</td>
                            <td>
                               {{employee.contact_no}}
                            </td>
                            <td><a href="{%url 'Employee:employee_detail_view' employee.id %}" class="btn btn-primary">Detail</a></td>
                        </tr>
                        {% endfor%}


                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}